In [1]:
import pandas as pd

import utility_functions as uf

In [19]:
uf.df_topics.columns

Index(['topic_id', 'topic_name', 'subfield_id', 'subfield_name', 'field_id',
       'field_name', 'domain_id', 'domain_name', 'keywords', 'summary',
       'wikipedia_url'],
      dtype='object')

In [23]:
(
    uf.df_topics
    .query("field_id == 14")
    .drop(["topic_id", "topic_name", "keywords", "summary", "wikipedia_url"], axis=1)
    .drop_duplicates()
    .sort_values(["subfield_id"])
)

,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
18,1402,Accounting,14,"Business, Management and Accounting",2,Social Sciences
2784,1403,Business and International Management,14,"Business, Management and Accounting",2,Social Sciences
163,1404,Management Information Systems,14,"Business, Management and Accounting",2,Social Sciences
57,1405,Management of Technology and Innovation,14,"Business, Management and Accounting",2,Social Sciences
144,1406,Marketing,14,"Business, Management and Accounting",2,Social Sciences
5,1407,Organizational Behavior and Human Resource Man...,14,"Business, Management and Accounting",2,Social Sciences
2,1408,Strategy and Management,14,"Business, Management and Accounting",2,Social Sciences
2398,1409,"Tourism, Leisure and Hospitality Management",14,"Business, Management and Accounting",2,Social Sciences
3086,1410,Industrial relations,14,"Business, Management and Accounting",2,Social Sciences

In [30]:
uf.df_topics.domain_name.unique()
uf.df_topics.domain_id.unique()

array([3, 2, 1, 4])

In [36]:
(
    uf.df_topics
    .query("domain_id == 4")
    .drop(["topic_id", "topic_name", "keywords", "summary", "wikipedia_url"], axis=1)
    .drop_duplicates()
    .sort_values(["subfield_id"])
)

,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
4129,2702,Anatomy,27,Medicine,4,Health Sciences
435,2703,Anesthesiology and Pain Medicine,27,Medicine,4,Health Sciences
34,2704,Biochemistry,27,Medicine,4,Health Sciences
64,2705,Cardiology and Cardiovascular Medicine,27,Medicine,4,Health Sciences
866,2706,Critical Care and Intensive Care Medicine,27,Medicine,4,Health Sciences
...,...,...,...,...,...,...
1669,3609,Occupational Therapy,36,Health Professions,4,Health Sciences
2065,3611,Pharmacy,36,Health Professions,4,Health Sciences
113,3612,"Physical Therapy, Sports Therapy and Rehabilit...",36,Health Professions,4,Health Sciences
808,3614,Radiological and Ultrasound Technology,36,Health Professions,4,Health Sciences
1357,3616,Speech and Hearing,36,Health Professions,4,Health Sciences

In [26]:
subfield_list = uf.df_topics.subfield_id.sort_values().unique()

subfield_distances = np.full((len(subfield_list), len(subfield_list)), np.nan, dtype=float)

for i, subfield_i in enumerate(subfield_list):
    for j in range(i, len(subfield_list)):

array([1100, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111,
       1200, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211,
       1212, 1213, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310,
       1311, 1312, 1313, 1314, 1315, 1402, 1403, 1404, 1405, 1406, 1407,
       1408, 1409, 1410, 1502, 1503, 1504, 1506, 1507, 1508, 1602, 1603,
       1604, 1605, 1606, 1607, 1702, 1703, 1704, 1705, 1706, 1707, 1708,
       1709, 1710, 1711, 1712, 1800, 1802, 1803, 1804, 1902, 1904, 1906,
       1907, 1908, 1910, 1911, 1912, 2000, 2002, 2003, 2100, 2102, 2103,
       2104, 2105, 2200, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209,
       2210, 2211, 2212, 2213, 2214, 2215, 2216, 2302, 2303, 2304, 2305,
       2306, 2307, 2308, 2309, 2310, 2311, 2312, 2402, 2403, 2404, 2405,
       2406, 2500, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2602, 2604,
       2605, 2607, 2608, 2610, 2611, 2612, 2613, 2614, 2702, 2703, 2704,
       2705, 2706, 2707, 2708, 2711, 2712, 2713, 2714, 2715, 2716, 2717,
       2718, 2720, 2721, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730,
       2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741,
       2742, 2743, 2745, 2746, 2747, 2748, 2802, 2803, 2804, 2805, 2806,
       2807, 2808, 2809, 2910, 2911, 2916, 2922, 3002, 3003, 3004, 3005,
       3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3200, 3202, 3203,
       3204, 3205, 3206, 3207, 3300, 3302, 3303, 3304, 3305, 3306, 3307,
       3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315, 3316, 3317, 3318,
       3319, 3320, 3321, 3322, 3402, 3404, 3500, 3504, 3505, 3506, 3600,
       3603, 3604, 3605, 3607, 3608, 3609, 3611, 3612, 3614, 3616])