In [54]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_distances
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from scipy.spatial.distance import squareform

import plotly.graph_objects as go

import utility_functions as uf

In [55]:
path = "data/"

In [60]:
df_country_subfield = (
    pd.read_csv(path+"df_country_subfield_norm_world_log.csv", index_col=0)
    .dropna(how="all", axis=1)
    .fillna(0)
)

In [61]:
len(df_country_subfield.columns)

252

In [62]:
df_country_subfield

,1100,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,3603,3604,3605,3607,3608,3609,3611,3612,3614,3616
country,,,,,,,,,,,,,,,,,,,,,
AD,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,3.113576,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
AE,-0.691529,0.046243,-1.051608,0.567711,-2.247748,-0.288924,0.000000,0.0,0.000000,-0.546693,...,0.000000,0.453564,0.451423,0.000000,0.0,0.000000,0.569795,0.000000,0.000000,0.253751
AF,0.000000,2.687943,0.000000,0.000000,1.492564,0.000000,0.000000,0.0,0.000000,0.628669,...,0.000000,2.807582,3.498588,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
AG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,4.309518,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
AL,0.000000,0.000000,0.000000,0.000000,0.763049,0.524648,2.224851,0.0,0.000000,-0.506311,...,0.000000,1.672602,0.000000,0.000000,0.0,0.000000,0.000000,1.677328,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XK,0.000000,2.310649,0.000000,2.138968,0.000000,0.589187,0.000000,0.0,0.000000,0.656840,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2.546518,0.000000,2.497200,0.000000
YE,0.000000,1.659647,1.254943,1.082502,-0.634345,0.631332,0.000000,0.0,0.363428,0.804346,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.440734,0.000000
ZA,0.683136,0.852924,0.873103,0.215154,1.091695,0.236589,1.119347,0.0,0.913147,0.531706,...,0.934918,0.336574,-0.188815,-0.538278,0.0,0.765286,0.622704,-2.261389,0.439855,0.099021
ZM,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.514753,0.0,0.000000,0.378126,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.930805,1.664079
ZW,0.879729,1.905183,0.000000,0.000000,0.000000,0.000000,1.883924,0.0,0.321283,0.405525,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.131862

In [63]:
from sklearn.preprocessing import StandardScaler
X_scaled = StandardScaler().fit_transform(df_country_subfield.values)

In [64]:
df_country_subfield.values.mean()

np.float64(0.050372069130574716)

In [65]:
X_scaled.mean()

np.float64(-4.8061602797625824e-20)

In [71]:
D = cosine_distances(df_country_subfield.values)
D_scaled = cosine_distances(X_scaled)
df_country_dist_cosine = pd.DataFrame(D,
                                     index=df_country_subfield.index,
                                     columns=df_country_subfield.index)
df_country_dist_cosine_scaled = pd.DataFrame(D_scaled,
                                     index=df_country_subfield.index,
                                     columns=df_country_subfield.index)
df_country_dist_cosine.to_csv(path+"df_country_dist_cosine_world_log.csv")
# df_country_dist_cosine.to_csv(path+"df_country_dist_cosine_scaled_world.csv")

/Users/irinavorobeva/PycharmProjects/geoscience/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/irinavorobeva/PycharmProjects/geoscience/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/irinavorobeva/PycharmProjects/geoscience/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/irinavorobeva/PycharmProjects/geoscience/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/irinavorobeva/PycharmProjects/geoscience/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/irinavorobeva/PycharmProjects/geoscience/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

In [67]:
df_country_dist_cosine

country,AD,AE,AF,AG,AL,AM,AO,AR,AS,AT,...,VG,VI,VN,VU,WS,XK,YE,ZA,ZM,ZW
country,,,,,,,,,,,,,,,,,,,,,
AD,0.000000,1.010035,0.970367,1.000000,1.045077,1.071946,0.951185,0.953860,1.000000,1.020633,...,1.000000,1.000000,1.007659,0.897467,0.804632,0.971496,0.927736,0.994518,0.948058,0.972629
AE,1.010035,0.000000,0.993837,1.033103,0.916297,1.061037,0.978482,1.201976,1.037087,1.084257,...,0.952641,1.045559,0.855534,1.125427,1.073693,1.027197,0.823164,0.938412,0.919861,0.902384
AF,0.970367,0.993837,0.000000,0.816524,0.881103,1.002821,0.871123,1.117433,0.936276,0.973096,...,0.981394,0.878885,0.952923,0.838524,0.890914,0.914620,0.913633,0.993739,0.761010,0.875148
AG,1.000000,1.033103,0.816524,0.000000,0.797182,0.981166,0.914720,1.108137,1.000000,0.887677,...,1.034716,1.000000,1.057031,0.972663,1.000000,0.967109,0.928481,1.093340,0.924380,0.962358
AL,1.045077,0.916297,0.881103,0.797182,0.000000,0.962571,0.979562,1.049321,0.969899,0.918591,...,1.010776,0.875828,1.056664,0.995675,0.984792,0.814669,0.877412,1.095599,0.822925,0.835823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XK,0.971496,1.027197,0.914620,0.967109,0.814669,0.884654,0.863744,1.069309,0.877227,1.085814,...,0.877248,0.936944,1.007437,0.849059,0.944371,0.000000,0.736364,1.092326,0.865815,0.873434
YE,0.927736,0.823164,0.913633,0.928481,0.877412,0.794796,0.965609,1.012825,0.972012,1.113755,...,0.926484,1.002084,0.878544,0.929526,0.970795,0.736364,0.000000,0.890031,0.773641,0.655426
ZA,0.994518,0.938412,0.993739,1.093340,1.095599,0.991359,0.891479,0.687256,0.995617,1.166453,...,0.975606,0.914041,0.920979,0.958160,0.951496,1.092326,0.890031,0.000000,0.782935,0.706522
ZM,0.948058,0.919861,0.761010,0.924380,0.822925,1.004277,0.841413,0.962136,0.940992,1.092245,...,0.917555,0.874457,0.959103,0.819399,0.940877,0.865815,0.773641,0.782935,0.000000,0.477650
ZW,0.972629,0.902384,0.875148,0.962358,0.835823,1.001891,0.748054,0.838812,0.950887,1.194130,...,0.956422,0.879294,0.913433,0.852292,0.986487,0.873434,0.655426,0.706522,0.477650,0.000000

In [68]:
# x_labels = [uf.id2name_country[country] for country in (map(str, df_country_dist_cosine.columns))]
# y_labels = [uf.id2name_country[country] for country in (map(str, df_country_dist_cosine.columns))]

sub_list = list(map(str, uf.top_n_countries_by_articles(20)))

# country = "AX"
# top_n = 20
# sub_list = df_country_dist_w1.sort_values(country, ascending=True)[[country]].head(top_n).index.to_list()

x_labels = sub_list
y_labels = sub_list

fig = go.Figure(
    data=go.Heatmap(
        # z=df_country_dist_cosine.values,
        z=df_country_dist_cosine.loc[sub_list, sub_list].values,
        x=x_labels,
        y=y_labels,
        colorscale="Viridis",
        zmin=0,
        zmax=1,
    )
)

# Layout
fig.update_layout(
    title="Distances for top-20 countries",
    width=1200,
    # height=20*len(y_labels),  # taller if more rows
    height=40*len(y_labels),  # taller if more rows
    margin=dict(l=100, r=50, t=50, b=100),
    xaxis=dict(tickangle=45, automargin=True),
    yaxis=dict(autorange="reversed", automargin=True)  # keep top-to-bottom ordering
)

fig.show()

In [70]:
# x_labels = [uf.id2name_country[country] for country in (map(str, df_country_dist_cosine.columns))]
# y_labels = [uf.id2name_country[country] for country in (map(str, df_country_dist_cosine.columns))]

sub_list = list(map(str, uf.top_n_countries_by_articles(20)))

# country = "AX"
# top_n = 20
# sub_list = df_country_dist_w1.sort_values(country, ascending=True)[[country]].head(top_n).index.to_list()

x_labels = sub_list
y_labels = sub_list

fig = go.Figure(
    data=go.Heatmap(
        # z=df_country_dist_cosine.values,
        z=df_country_dist_cosine_scaled.loc[sub_list, sub_list].values,
        x=x_labels,
        y=y_labels,
        colorscale="Viridis",
        zmin=-1,
        zmax=1,
    )
)

# Layout
fig.update_layout(
    title="Distances for top-20 countries",
    width=1200,
    # height=20*len(y_labels),  # taller if more rows
    height=40*len(y_labels),  # taller if more rows
    margin=dict(l=100, r=50, t=50, b=100),
    xaxis=dict(tickangle=45, automargin=True),
    yaxis=dict(autorange="reversed", automargin=True)  # keep top-to-bottom ordering
)

fig.show()