In [1]:
# What are the specific areas of interests in different countries

In [5]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

import utility_functions as uf

In [6]:

path = "data/"

df_country_subfield = pd.read_csv(path+"df_country_subfield.csv", index_col="country")

In [7]:
df_country_subfield

,1100,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,3603,3604,3605,3607,3608,3609,3611,3612,3614,3616
country,,,,,,,,,,,,,,,,,,,,,
AD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AE,1.0,3.0,1.0,3.0,1.0,6.0,NaN,NaN,NaN,13.0,...,NaN,4.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0
AF,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,...,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,NaN,NaN,NaN,NaN,3.0,2.0,1.0,NaN,NaN,2.0,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XK,NaN,2.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN
YE,NaN,3.0,2.0,1.0,1.0,3.0,NaN,NaN,1.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
ZA,30.0,51.0,52.0,16.0,214.0,77.0,17.0,NaN,66.0,290.0,...,6.0,27.0,8.0,2.0,NaN,16.0,16.0,1.0,14.0,13.0
ZM,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
ZW,1.0,4.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [8]:
df_country_subfield_norm = (
    df_country_subfield
    .div(df_country_subfield.sum(axis=1), axis=0)
)

In [9]:
df_world_subfield = (
    df_country_subfield.sum(axis=0)
    .to_frame()
    .T
)

df_world_subfield_norm = (
    df_world_subfield
    .div(df_world_subfield.sum(axis=1), axis=0)
)
df_world_subfield_norm

,1100,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,3603,3604,3605,3607,3608,3609,3611,3612,3614,3616
0,0.001317,0.001889,0.001888,0.001122,0.006244,0.005284,0.000483,0.000042,0.002302,0.014814,...,0.000205,0.001676,0.00084,0.000298,0.000036,0.000647,0.000746,0.000834,0.000784,0.001024

In [10]:
df_country_subfield_norm_world = (
    df_country_subfield_norm
    .div(df_world_subfield_norm.loc[0])
)
df_country_subfield_norm_world_norm = (
    df_country_subfield_norm_world
    .div(df_country_subfield_norm_world.sum(axis=1), axis=0)
)
df_country_subfield_norm_world

,1100,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,3603,3604,3605,3607,3608,3609,3611,3612,3614,3616
country,,,,,,,,,,,,,,,,,,,,,
AD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.501358,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AE,0.500810,1.047329,0.349376,1.764223,0.105637,0.749069,NaN,NaN,NaN,0.578861,...,NaN,1.573912,1.570546,NaN,NaN,NaN,1.767904,NaN,NaN,1.288851
AF,NaN,14.701401,NaN,NaN,4.448485,NaN,NaN,NaN,NaN,1.875113,...,NaN,16.569796,33.068720,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,74.404619,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,NaN,NaN,NaN,NaN,2.144805,1.689864,9.252101,NaN,NaN,0.602715,...,NaN,5.326006,NaN,NaN,NaN,NaN,NaN,5.351237,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XK,NaN,10.080961,NaN,8.490674,NaN,1.802522,NaN,NaN,NaN,1.928688,...,NaN,NaN,NaN,NaN,NaN,NaN,12.762583,NaN,12.148435,NaN
YE,NaN,5.257455,3.507638,2.952056,0.530283,1.880114,NaN,NaN,1.438252,2.235234,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.223794,NaN
ZA,1.980077,2.346498,2.394329,1.240053,2.979321,1.266921,3.062853,NaN,2.492153,1.701833,...,2.547004,1.400143,0.827940,0.583752,NaN,2.149609,1.863961,0.104206,1.552482,1.104089
ZM,NaN,NaN,NaN,NaN,NaN,NaN,33.607631,NaN,NaN,1.459548,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.895058,5.280806
ZW,2.410246,6.720640,NaN,NaN,NaN,NaN,6.579272,NaN,1.378895,1.500091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.101426

In [11]:
country = "FR"

In [19]:
# df_country_subfield_norm_world_norm.to_csv(path+"df_country_subfield_norm_world.csv")

In [12]:
df_plot = pd.concat([
    df_country_subfield_norm.loc[country],
    df_world_subfield_norm.loc[0],
    # df_country_subfield_norm_world.loc[country],
    df_country_subfield_norm_world_norm.loc[country]
], axis=1)
df_plot.columns = ["share_norm", "share_norm_world", "representation_norm"]
# df_plot

In [13]:
x = df_country_subfield_norm.columns.to_list()

y1 = df_country_subfield_norm.loc[country]          # left axis
y2 = df_world_subfield_norm.loc[0]      # left axis
y3 = df_country_subfield_norm_world.loc[country]    # right axis (different scale)

fig = go.Figure()

# Left y-axis lines
fig.add_trace(
    go.Scatter(
        x=x,
        y=y1,
        mode="lines",
        name="Sub-field share across the country (left)",

    )
)

fig.add_trace(
    go.Scatter(
        x=x,
        y=y2,
        mode="lines",
        name="Sub-field share across the world (left)",

    )
)

# Right y-axis line
fig.add_trace(
    go.Bar(
        x=x,
        y=y3,
        name="Subfield representation (right)",
        yaxis="y2",
        marker=dict(
            color="grey",
            opacity=0.4
        )
    )
)

fig.add_trace(
    go.Scatter(
        x=x,                         # same x-range as other traces
        y=[1] * len(x),              # constant line at y = 1
        mode="lines",
        name="Representation = 1 (right)",
        line=dict(color="grey", dash="dash"),
        showlegend=True,
        yaxis="y2",
    )
)

# Layout with secondary y-axis
fig.update_layout(
    title=uf.get_country_info(country).iloc[0, 0],
    xaxis=dict(title="Sub-field"),
    yaxis=dict(title="Sub-field share", overlaying="y2",),
    yaxis2=dict(
        title="Representation (1 = as in the world)",

        side="right"
    ),
    legend=dict(x=0.01, y=0.99),
    margin=dict(l=60, r=60, t=40, b=40)
)

fig.show()

In [14]:
uf.get_subfield_info(1410)

,subfield_id,subfield_name,field_name,domain_name
3086,1410,Industrial relations,"Business, Management and Accounting",Social Sciences

In [20]:
top_20_countries_list = uf.top_n_countries_by_articles(20)
top_20_countries_list

['SE',
 'BE',
 'CH',
 'TW',
 'RU',
 'PL',
 'NL',
 'KR',
 'IN',
 'AU',
 'BR',
 'IT',
 'ES',
 'CA',
 'JP',
 'FR',
 'DE',
 'GB',
 'CN',
 'US']

In [24]:
x_labels = list(map(str, df_country_subfield_norm_world.columns))
# y_labels = list(map(str, df_country_subfield_norm_world.index))

# sub_list = list(map(str, top_20_countries_list))
sub_list = ["FR", "ES", "SI", "PT", "AE", "IT", "BE", "HR", "LV"]
y_labels = sub_list

fig = go.Figure(
    data=go.Heatmap(
        # z=df_country_subfield_norm.values,
        z=df_country_subfield_norm.loc[sub_list].values,
        x=x_labels,
        y=y_labels,
        colorscale="Viridis",
        zmin=0,
        zmax=0.01,
    )
)

# Layout
fig.update_layout(
    title="Sub-field share by country",
    width=1000,
    # height=20*len(y_labels),  # taller if more rows
    height=40*len(y_labels),  # taller if more rows
    margin=dict(l=100, r=50, t=50, b=100),
    xaxis=dict(tickangle=45, automargin=True),
    yaxis=dict(autorange="reversed", automargin=True)  # keep top-to-bottom ordering
)

fig.show()

In [25]:
x_labels = list(map(str, df_country_subfield_norm_world.columns))
# y_labels = list(map(str, df_country_subfield_norm_world.index))

# sub_list = list(map(str, top_20_countries_list))
sub_list = ["FR", "ES", "SI", "PT", "AE", "IT", "BE", "HR", "LV"]

y_labels = sub_list

fig = go.Figure(
    data=go.Heatmap(
        # z=df_country_subfield_norm_world_norm.values,
        z=df_country_subfield_norm_world.loc[sub_list].values,
        x=x_labels,
        y=y_labels,
        colorscale="Viridis",
        zmin=0,
        zmax=2,
    )
)

# Layout
fig.update_layout(
    title="Representation vs The world",
    width=1000,
    # height=20*len(y_labels),  # taller if more rows
    height=40*len(y_labels),  # taller if more rows
    margin=dict(l=100, r=50, t=50, b=100),
    xaxis=dict(tickangle=45, automargin=True),
    yaxis=dict(autorange="reversed", automargin=True)  # keep top-to-bottom ordering
)

fig.show()

In [27]:
x_labels = list(map(str, df_country_subfield_norm_world.columns))
# y_labels = list(map(str, df_country_subfield_norm_world.index))

# sub_list = list(map(str, top_20_countries_list))
sub_list = ["FR", "ES", "SI", "PT", "AE", "IT", "BE", "HR", "LV"]
y_labels = sub_list

fig = go.Figure(
    data=go.Heatmap(
        # z=df_country_subfield_norm_world_norm.values,
        z=df_country_subfield_norm_world_norm.loc[sub_list].values,
        x=x_labels,
        y=y_labels,
        colorscale="Viridis",
        zmin=0,
        zmax=0.01,
    )
)

# Layout
fig.update_layout(
    title="Representation vs The world (normalised by country)",
    width=1000,
    # height=20*len(y_labels),  # taller if more rows
    height=40*len(y_labels),  # taller if more rows
    margin=dict(l=100, r=50, t=50, b=100),
    xaxis=dict(tickangle=45, automargin=True),
    yaxis=dict(autorange="reversed", automargin=True)  # keep top-to-bottom ordering
)

fig.show()

In [ ]:
fig = px.line()

In [32]:

countries = ["FR", "ES", "SI", "PT", "AE", "IT", "BE", "HR", "LV"]
# Create figure
fig = go.Figure()

for country in countries:
    fig.add_trace(
        go.Scatter(
            x=df_country_subfield_norm_world_norm.index,
            y=df_country_subfield_norm_world_norm.loc[country].values,
            name=country,
            orientation='h',
            mode='lines',
        )
    )

fig.add_trace(
    go.Scatter(
        x=df_country_subfield_norm_world_norm.index,
        y=df_country_subfield_norm_world_norm.loc[countries].mean().values,
        name="Mean",
        orientation='h',
        mode='lines',
    )
)

# Layout
fig.update_layout(
    barmode='group',       # 'stack' if you prefer stacked bars
    title=f"Distribution",
    xaxis_title="Value",
    yaxis_title=None,
    margin=dict(l=150),    # leave space for long y labels
)

# Optional: largest bar at top
fig.update_yaxes(autorange="reversed")

fig.show()