In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_distances
# from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
# from scipy.spatial.distance import squareform

import plotly.graph_objects as go

from Irina import utility_functions as uf

In [2]:
path = "../data/"

In [3]:
df_country_subfield = (
    pd.read_csv(path+"df_country_subfield_norm_world_log.csv", index_col=0)
    .dropna(how="all", axis=1)
    .fillna(0)
)

In [4]:
df_country_subfield

,1100,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,3603,3604,3605,3607,3608,3609,3611,3612,3614,3616
country,,,,,,,,,,,,,,,,,,,,,
AE,-0.141324,0.250685,-0.458084,0.817151,0.000000,-0.104415,0.000000,0.0,0.000000,-0.837127,...,0.000000,0.647821,0.254382,0.000000,0.0,0.000000,1.064201,0.0,0.000000,0.068773
AF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.771716,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
AG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
AL,0.000000,0.000000,0.000000,0.000000,0.252742,0.263719,0.000000,0.0,0.000000,-0.692137,...,0.000000,1.996784,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
AM,0.000000,0.000000,0.000000,0.000000,0.211069,-0.183418,0.000000,0.0,0.105759,0.000000,...,0.000000,0.163352,0.868525,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.682917
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XK,0.000000,0.000000,0.000000,0.000000,0.000000,1.187128,0.000000,0.0,0.000000,0.231271,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,3.057250,0.000000
YE,0.000000,0.000000,1.465981,0.000000,0.000000,0.433356,0.000000,0.0,1.415681,0.576112,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,2.303478,0.000000
ZA,0.606150,0.694476,0.882454,0.391904,0.919764,0.182535,1.223860,0.0,0.805486,0.415442,...,1.159073,-0.182891,-0.096757,-1.088636,0.0,0.420583,0.782056,0.0,0.279589,0.074310
ZM,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.564803,0.0,0.000000,0.162278,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
ZW,1.486690,1.878699,0.000000,0.000000,0.000000,0.000000,2.583974,0.0,1.119631,0.280061,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,1.696788

In [5]:
D = cosine_distances(df_country_subfield.values)

df_country_dist_cosine = pd.DataFrame(D,
                                     index=df_country_subfield.index,
                                     columns=df_country_subfield.index)

# df_country_dist_cosine.to_csv(path+"df_country_dist_cosine_world_log.csv")

/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [6]:
df_country_dist_cosine

country,AE,AF,AG,AL,AM,AO,AR,AT,AU,AW,...,VG,VI,VN,VU,WS,XK,YE,ZA,ZM,ZW
country,,,,,,,,,,,,,,,,,,,,,
AE,0.000000,0.938449,0.961056,0.927180,1.007075,0.955215,1.157515,1.012626,0.901767,0.877329,...,0.926928,1.073743,0.759943,1.073153,0.917091,0.973749,0.843612,0.896756,0.922834,0.792702
AF,0.938449,0.000000,1.000000,0.984376,1.012692,0.927480,1.091100,0.934056,0.957745,0.974683,...,0.968737,0.943668,1.053019,0.859540,1.000000,0.913189,0.933446,1.041413,0.721543,0.996573
AG,0.961056,1.000000,0.000000,0.840750,1.014244,1.000000,1.077217,0.969353,0.957418,1.000000,...,1.020580,1.000000,1.107274,1.000000,1.000000,0.951231,0.889278,1.084343,0.885036,0.957525
AL,0.927180,0.984376,0.840750,0.000000,0.935863,0.932609,1.118746,0.917591,0.964441,0.950248,...,0.918731,0.848063,1.086697,1.015335,1.032129,0.847453,0.790696,1.054896,0.878272,0.832310
AM,1.007075,1.012692,1.014244,0.935863,0.000000,1.028918,0.949279,0.917580,1.238948,1.002050,...,0.951651,1.005741,0.868422,1.030590,1.095617,0.919660,0.809193,1.040736,1.070374,0.993911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XK,0.973749,0.913189,0.951231,0.847453,0.919660,0.924192,1.075948,1.040147,1.023416,1.013941,...,0.850804,0.904126,1.055005,1.009727,0.874864,0.000000,0.773695,1.088973,0.919805,0.881013
YE,0.843612,0.933446,0.889278,0.790696,0.809193,0.965283,1.038507,1.057895,1.048915,0.956104,...,0.875916,0.956450,0.935844,0.946789,1.022033,0.773695,0.000000,0.891019,0.828656,0.694331
ZA,0.896756,1.041413,1.084343,1.054896,1.040736,0.935422,0.701109,1.100601,0.688492,0.853981,...,1.026166,0.961309,0.986096,0.995373,0.944508,1.088973,0.891019,0.000000,0.858933,0.715264
ZM,0.922834,0.721543,0.885036,0.878272,1.070374,0.891466,1.046378,1.057837,0.837288,0.891220,...,1.023705,0.908622,0.981172,0.863808,0.865109,0.919805,0.828656,0.858933,0.000000,0.681719
ZW,0.792702,0.996573,0.957525,0.832310,0.993911,0.762700,0.851709,1.153216,0.935739,0.646063,...,0.926471,0.989213,0.919962,0.942736,0.981937,0.881013,0.694331,0.715264,0.681719,0.000000

In [7]:
subset = uf.top_n_countries_by_articles(30)

fig = uf.plotly_heatmap(
    # df_country_dist_cosine,
    # y_labels=df_country_dist_cosine.index.astype(str).to_list(),
    # x_labels=df_country_dist_cosine.columns.astype(str).to_list(),
    df_country_dist_cosine.loc[subset, subset],
    y_labels=subset,
    x_labels=subset,
    y_type="country",
    x_type="country",
    y_name="X-Country",
    x_name="Y-Country",
    title="Cosine distance",
    line_height=30,
    z_min=0, z_max=2
)

In [10]:
# country_list = ["US", "CN", "GB"]  # list of countries
country_list = ["US", "FR", "GB"]  # list of countries
x = df_country_subfield.columns.to_list()

fig = go.Figure()

for country in country_list:
    y = df_country_subfield.loc[country].values
    y_safe = [v if not np.isnan(v) else None for v in y]  # handle NaNs

    fig.add_trace(go.Scatter(
        x=x,
        y=y_safe,
        mode="lines",
        name=f"{uf.id2name_country[country]}"
    ))

fig.update_layout(
    title="Interest distributions for selected countries",
    xaxis=dict(title="Sub-field"),
    yaxis=dict(title="Sub-field share"),
    legend=dict(x=0.01, y=0.99),
    margin=dict(l=60, r=60, t=40, b=40)
)

fig.show()