In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import irina.utility_functions as uf

In [3]:
year = 2022
mode = "individual"

In [5]:
subfield_tree = uf.get_subfield_tree(uf.df_topics)

In [6]:
df_cs = pd.read_csv(uf.PATH+f"df_country_subfield/{mode}_{year}.csv", index_col=0)
df_prob = df_cs.div(df_cs.sum(axis=1), axis=0)

In [7]:
df_dist = uf.get_w1_distances(subfield_tree, df_prob)
np.fill_diagonal(df_dist.values, np.nan)

In [11]:
df_stats = (
    pd.read_csv(uf.PATH+f"df_country_stats_yearly.csv", index_col=0)
    .query("year == @year and mode == @mode")
    .drop(["year", "mode"], axis=1)
)

In [12]:
df_stats

          entropy  norm_entropy  total_articles  log_total_articles      gini
country
AD       2.163956      0.391352            10.0            2.302585  0.088889
AE       4.641234      0.839369          4503.0            8.412499  0.625381
AF       3.927882      0.710359           336.0            5.817111  0.551527
AG       3.369488      0.609374            73.0            4.290459  0.338393
AL       4.418953      0.799170           768.0            6.643790  0.531915
...           ...           ...             ...                 ...       ...
WS       2.625048      0.474741            19.0            2.944439  0.175439
YE       4.490146      0.812045           436.0            6.077642  0.470705
ZA       4.696691      0.849399         19991.0            9.903037  0.642609
ZM       4.395550      0.794937           617.0            6.424869  0.529203
ZW       4.144342      0.749506          1004.0            6.911747  0.606901

[214 rows x 5 columns]

In [13]:
df_stats.loc["US"]

entropy                    4.487516
norm_entropy               0.811569
total_articles        776880.000000
log_total_articles        13.563041
gini                       0.685946
Name: US, dtype: float64

In [15]:
df_stats.sort_values(by=["norm_entropy"], ascending=False)

          entropy  norm_entropy  total_articles  log_total_articles      gini
country
BG       4.872704      0.881231          5774.0            8.661120  0.556386
ES       4.865402      0.879910         76103.0           11.239843  0.600309
PT       4.865197      0.879873         22515.0           10.021937  0.590005
RO       4.840580      0.875421         15394.0            9.641733  0.596873
IT       4.837267      0.874822         83726.0           11.335305  0.610017
...           ...           ...             ...                 ...       ...
FK       1.039721      0.188034             4.0            1.386294  0.166667
TO       0.693147      0.125356             2.0            0.693147  0.000000
SJ       0.636514      0.115114             3.0            1.098612  0.166667
MP      -0.000000     -0.000000             1.0            0.000000  0.000000
KI      -0.000000     -0.000000             1.0            0.000000  0.000000

[214 rows x 5 columns]

In [16]:
uf.get_country_info("BG")

        name  region      sub-region code
34  Bulgaria  Europe  Eastern Europe   BG

In [164]:
countries_sorted = df_stats.sort_values(by=["total_articles", "norm_entropy"], ascending=False).head(10).index.to_list()
(
    df_dist
    .loc[countries_sorted, countries_sorted]
    .apply(uf.top_n_columns)
    .T
)

     0   1   2   3   4
US  ID  BR  CN  TR  RU
CN  ID  TR  BR  GB  DE
ID  CN  JP  IN  US  DE
IN  ID  BR  TR  GB  DE
DE  ID  CN  JP  IN  BR
BR  CN  JP  IN  RU  US
RU  ID  JP  BR  TR  GB
GB  CN  IN  ID  JP  RU
JP  ID  BR  TR  RU  GB
TR  CN  JP  IN  RU  US

In [97]:
level1 = ["US", "ID", "CN", "BR"]
level2 = ['GB', 'ES', 'AU', 'PL', 'NL', 'MX']

In [80]:
(
    df_dist
    .loc[level1]
    .apply(lambda row: uf.bottom_n_columns(row, 10), axis=1)
)

US    [SG, GR, IR, BG, MA, TH, TW, KW, IT, SA]
ID    [MZ, ZW, GE, UZ, PA, SV, BI, SS, PE, TJ]
CN    [IN, DZ, IQ, BY, KR, KP, CZ, IR, BG, AE]
BR    [CO, HN, TZ, GH, TR, TT, VE, JM, PS, ZA]
dtype: object

In [151]:
df_dist.loc[countries_sorted, countries_sorted]

,US,CN,ID,IN,DE,BR,RU,GB,JP,TR,...,EG,UA,TW,MY,CH,PT,NG,ZA,PK,SE
US,NaN,0.225177,0.402225,0.128899,0.121347,0.240214,0.186863,0.174106,0.128821,0.216891,...,0.179230,0.200712,0.083351,0.181316,0.105998,0.130142,0.186581,0.237704,0.136308,0.102264
CN,0.225177,NaN,0.502688,0.108512,0.266802,0.388535,0.218808,0.381635,0.197048,0.396267,...,0.263361,0.296773,0.203036,0.270423,0.290035,0.327696,0.298198,0.351029,0.315717,0.302072
ID,0.402225,0.502688,NaN,0.463848,0.294702,0.182247,0.292712,0.266475,0.498762,0.202586,...,0.476078,0.221590,0.456383,0.238624,0.316455,0.282063,0.270241,0.174854,0.291864,0.309107
IN,0.128899,0.108512,0.463848,NaN,0.188969,0.305666,0.184550,0.281620,0.125390,0.292597,...,0.172452,0.261513,0.104238,0.236026,0.192004,0.227352,0.227504,0.305524,0.209682,0.203612
DE,0.121347,0.266802,0.294702,0.188969,NaN,0.145819,0.120649,0.118122,0.211334,0.135961,...,0.231889,0.106101,0.172610,0.110423,0.064168,0.068772,0.087417,0.129179,0.083743,0.058502
BR,0.240214,0.388535,0.182247,0.305666,0.145819,NaN,0.248339,0.119338,0.337893,0.060924,...,0.311218,0.158303,0.305166,0.187490,0.151512,0.137739,0.114013,0.071501,0.131690,0.155497
RU,0.186863,0.218808,0.292712,0.184550,0.120649,0.248339,NaN,0.226957,0.281775,0.236480,...,0.333148,0.123454,0.223078,0.095882,0.176538,0.174732,0.186426,0.187690,0.188061,0.169894
GB,0.174106,0.381635,0.266475,0.281620,0.118122,0.119338,0.226957,NaN,0.244049,0.075992,...,0.227354,0.177659,0.203491,0.185176,0.095202,0.060340,0.115891,0.133304,0.078062,0.081444
JP,0.128821,0.197048,0.498762,0.125390,0.211334,0.337893,0.281775,0.244049,NaN,0.312892,...,0.083151,0.293859,0.070161,0.278833,0.191419,0.225077,0.260298,0.337262,0.214562,0.197492
TR,0.216891,0.396267,0.202586,0.292597,0.135961,0.060924,0.236480,0.075992,0.312892,NaN,...,0.289727,0.144564,0.271331,0.171522,0.126112,0.094059,0.124282,0.079879,0.105297,0.121179
FR,0.213709,0.338013,0.201666,0.284312,0.102854,0.084690,0.179119,0.118321,0.309194,0.071977,...,0.293010,0.093168,0.270673,0.122609,0.123004,0.095970,0.101164,0.040290,0.122928,0.120180
IT,0.088575,0.281971,0.382190,0.183235,0.120699,0.219149,0.229372,0.124300,0.122537,0.193764,...,0.116027,0.216264,0.092811,0.224578,0.078856,0.105396,0.162535,0.217555,0.108848,0.080069
ES,0.167997,0.372836,0.246482,0.272387,0.113563,0.098869,0.217653,0.034720,0.263727,0.055603,...,0.245195,0.150726,0.222843,0.158871,0.089838,0.052900,0.108415,0.108491,0.070793,0.077637
KR,0.118572,0.167650,0.494859,0.093483,0.212349,0.334505,0.243728,0.243248,0.048750,0.309724,...,0.118969,0.290005,0.042957,0.263134,0.193213,0.222217,0.269525,0.333648,0.213871,0.196383
CA,0.103443,0.305891,0.320591,0.207903,0.077152,0.160376,0.189467,0.077555,0.188197,0.132001,...,0.171920,0.172501,0.151414,0.179564,0.030981,0.042518,0.106454,0.153389,0.053720,0.022656
AU,0.162033,0.368983,0.297825,0.269756,0.114566,0.144580,0.221477,0.039195,0.212372,0.110433,...,0.193668,0.202452,0.173659,0.209218,0.087470,0.066168,0.123203,0.158197,0.068296,0.070387
IR,0.072795,0.181753,0.450094,0.079907,0.167063,0.284647,0.219471,0.207088,0.075887,0.259374,...,0.122537,0.245385,0.048510,0.218125,0.147313,0.175638,0.209067,0.283848,0.162447,0.149589
PL,0.208643,0.310850,0.209600,0.271808,0.096389,0.096383,0.158223,0.135188,0.301003,0.093600,...,0.280461,0.073687,0.260372,0.103074,0.118359,0.103271,0.104151,0.046591,0.126202,0.112934
NL,0.151812,0.356102,0.302127,0.256648,0.108074,0.142365,0.220812,0.041975,0.205471,0.113752,...,0.189701,0.204959,0.169824,0.211775,0.071096,0.067096,0.115755,0.161908,0.056917,0.063424
MX,0.189949,0.280966,0.260322,0.231774,0.089244,0.119482,0.166771,0.121228,0.263141,0.133879,...,0.226627,0.117068,0.251049,0.129952,0.092578,0.087822,0.036083,0.093103,0.084411,0.102481
EG,0.179230,0.263361,0.476078,0.172452,0.231889,0.311218,0.333148,0.227354,0.083151,0.289727,...,NaN,0.319783,0.124496,0.326852,0.178113,0.205609,0.216800,0.313065,0.190701,0.181904
UA,0.200712,0.296773,0.221590,0.261513,0.106101,0.158303,0.123454,0.177659,0.293859,0.144564,...,0.319783,NaN,0.251589,0.049033,0.163884,0.143320,0.143403,0.097879,0.170039,0.153678
TW,0.083351,0.203036,0.456383,0.104238,0.172610,0.305166,0.223078,0.203491,0.070161,0.271331,...,0.124496,0.251589,NaN,0.223452,0.167794,0.183053,0.247501,0.294796,0.191533,0.156276
MY,0.181316,0.270423,0.238624,0.236026,0.110423,0.187490,0.095882,0.185176,0.278833,0.171522,...,0.326852,0.049033,0.223452,NaN,0.171453,0.146734,0.151754,0.123733,0.176697,0.160302
CH,0.105998,0.290035,0.316455,0.192004,0.064168,0.151512,0.176538,0.095202,0.191419,0.126112,...,0.178113,0.163884,0.167794,0.171453,NaN,0.048990,0.091073,0.149672,0.043299,0.024456
PT,0.130142,0.327696,0.282063,0.227352,0.068772,0.137739,0.174732,0.060340,0.225077,0.094059,...,0.205609,0.143320,0.183053,0.146734,0.048990,NaN,0.080715,0.114118,0.040734,0.031569
NG,0.186581,0.298198,0.270241,0.227504,0.087417,0.114013,0.186426,0.115891,0.260298,0.124282,...,0.216800,0.143403,0.247501,0.151754,0.091073,0.080715,NaN,0.104170,0.064220,0.099079
ZA,0.237704,0.351029,0.174854,0.305524,0.129179,0.071501,0.187690,0.133304,0.337262,0.079879,...,0.313065,0.097879,0.294796,0.123733,0.149672,0.114118,0.104170,NaN,0.127850,0.142646
PK,0.136308,0.315717,0.291864,0.209682,0.083743,0.131690,0.188061,0.078062,0.214562,0.105297,...,0.190701,0.170039,0.191533,0.176697,0.043299,0.040734,0.064220,0.127850,NaN,0.046682
SE,0.102264,0.302072,0.309107,0.203612,0.058502,0.155497,0.169894,0.081444,0.197492,0.121179,...,0.181904,0.153678,0.156276,0.160302,0.024456,0.031569,0.099079,0.142646,0.046682,NaN

In [161]:
def get_base(df_dist, df_stats, c_list, grouped_list):
    non_grouped = [c for c in df_dist.index if (c not in grouped_list) and (c not in c_list)]
    countries_sorted = (
        df_stats
        .loc[non_grouped]
        .sort_values(by=["total_articles", "norm_entropy"], ascending=False)
        .head(10)
        .index
        .to_list()
    )
    display(
        df_dist
        .loc[countries_sorted, countries_sorted]
        .max(axis=1)
        .to_frame("dist_max")
        .assign(
            c_max = df_dist.loc[countries_sorted, countries_sorted].apply(lambda row: uf.top_n_columns(row, 1), axis=1),
        )
        .sort_values("dist_max", ascending=False)
    )

    return

In [162]:
get_base(df_dist, df_stats, [], [])

    dist_max c_max
CN  0.502688    ID
ID  0.502688    CN
JP  0.498762    ID
IN  0.463848    ID
US  0.402225    ID
TR  0.396267    CN
BR  0.388535    CN
GB  0.381635    CN
DE  0.294702    ID
RU  0.292712    ID

In [ ]:
c_list = ["US", "CN", "ID", "BR"]
grouped = []
non_grouped = df_dist
while

In [134]:
c_list = level1 + ["GB", "PL"]
test_array = np.zeros((len(c_list), len(c_list)))
n=20
level1_step1_list = []

group_dict = {}
for i, c1 in enumerate(c_list):
    c1_list = df_dist.loc[[c1]].apply(lambda row: uf.bottom_n_columns(row, n), axis=1).iloc[0]
    level1_step1_list += c1_list
    group_dict[c1] = c1_list
    for j, c2 in enumerate(c_list):
        c2_list = df_dist.loc[[c2]].apply(lambda row: uf.bottom_n_columns(row, n), axis=1).iloc[0]
        test_array[i, j] = len(list(set(c1_list) & set(c2_list)))
level1_step2_list = list(set(level1_step1_list))

In [136]:
non_grouped = [c for c in df_dist.index.to_list() if c not in level1_step2_list]

In [138]:
[c for c in countries_sorted if (c not in level1_step2_list) and (c not in c_list)]

['IN',
 'DE',
 'RU',
 'JP',
 'TR',
 'FR',
 'IT',
 'ES',
 'KR',
 'CA',
 'AU',
 'IR',
 'NL',
 'MX',
 'UA',
 'TW',
 'CH',
 'PT',
 'ZA',
 'PK',
 'SE']

In [122]:
countries_sorted = df_stats.sort_values(by=["total_articles", "norm_entropy"], ascending=False).head(30).index.to_list()

In [139]:
c_list

['US', 'ID', 'CN', 'BR', 'GB', 'PL']

In [140]:
pd.DataFrame(test_array, index=c_list, columns=c_list)

      US    ID    CN    BR    GB    PL
US  16.0   2.0  11.0   5.0   7.0   8.0
ID   2.0  19.0   4.0   7.0   2.0   8.0
CN  11.0   4.0  18.0   4.0   3.0   9.0
BR   5.0   7.0   4.0  18.0   9.0  12.0
GB   7.0   2.0   3.0   9.0  18.0   8.0
PL   8.0   8.0   9.0  12.0   8.0  18.0

In [141]:
list(set(group_dict["US"]) & set(group_dict["CN"]))

['PL', 'GU', 'MY', 'BJ', 'NG', 'AM', 'BF', 'EG', 'GB', 'BR', 'LU']

In [120]:
pd.DataFrame.from_dict(group_dict).melt(var_name="group", value_name="country")

    group country
0      US      SG
1      US      GR
2      US      IR
3      US      BG
4      US      MA
..    ...     ...
115    PL      PH
116    PL      PS
117    PL      NO
118    PL      LK
119    PL      TR

[120 rows x 2 columns]