In [32]:
import pandas as pd
import numpy as np
import importlib

from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from scipy.spatial.distance import squareform

import plotly.express as px
import plotly.graph_objects as go

import irina.utility_functions as uf

In [56]:
year = 2023
mode = "collaborative_"

In [57]:
df_cs = pd.read_csv(uf.PATH+f"df_country_subfield/{mode}{year}.csv", index_col=0)
df_prob = df_cs.div(df_cs.sum(axis=1), axis=0)

In [58]:
df_prob

,1100,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,3603,3604,3605,3607,3608,3609,3611,3612,3614,3616
country,,,,,,,,,,,,,,,,,,,,,
AD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.076923,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AE,0.000406,0.000913,0.001115,0.000507,0.000608,0.007300,0.000101,0.000101,0.000507,0.014296,...,0.000608,0.001622,0.002535,0.000101,NaN,0.000304,0.000203,0.000507,0.001217,0.000913
AF,0.012500,0.010000,0.002500,NaN,0.005000,0.015000,NaN,NaN,0.007500,0.037500,...,NaN,0.005000,NaN,NaN,NaN,NaN,NaN,0.002500,0.010000,0.002500
AG,NaN,0.002703,NaN,NaN,NaN,0.002703,NaN,NaN,NaN,NaN,...,NaN,0.008108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,0.002353,0.007059,0.009412,0.007059,NaN,0.014118,NaN,NaN,0.002353,0.016471,...,0.004706,NaN,NaN,NaN,NaN,NaN,0.004706,NaN,0.002353,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WS,0.029412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.058824,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YE,0.001517,0.003794,0.002276,0.002276,0.003035,0.008346,NaN,NaN,0.002276,0.019727,...,0.003794,0.000759,0.002276,0.001517,NaN,NaN,NaN,0.000759,0.002276,NaN
ZA,0.003345,0.003903,0.003265,0.001673,0.012902,0.007646,0.001035,NaN,0.005973,0.024450,...,0.000239,0.001673,0.001115,0.000558,NaN,0.001593,0.000558,0.000478,0.002310,0.001513
ZM,0.012717,0.005780,0.003468,0.001156,0.008092,0.008092,0.001156,0.004624,0.009249,0.024277,...,NaN,0.001156,0.005780,NaN,NaN,NaN,0.001156,NaN,0.003468,0.002312
ZW,0.008705,0.004353,0.002176,NaN,0.013058,0.007617,0.003264,NaN,0.009793,0.021763,...,NaN,0.001088,NaN,0.001088,NaN,NaN,NaN,NaN,0.001088,0.001088

In [59]:
subfield_tree = uf.get_subfield_tree(uf.df_topics)

In [60]:
importlib.reload(uf)

In [61]:
df_dist = uf.get_w1_distances(subfield_tree, df_prob)

In [62]:
df_dist

,AD,AE,AF,AG,AL,AM,AO,AR,AS,AT,...,VE,VG,VI,VN,VU,WS,YE,ZA,ZM,ZW
AD,0.000000,0.295304,0.110109,0.499580,0.142680,0.300964,0.230637,0.295395,0.499053,0.246220,...,0.134062,0.704243,0.297908,0.330399,0.296584,0.333843,0.238355,0.192933,0.274351,0.077526
AE,0.295304,0.000000,0.279710,0.608565,0.211407,0.124880,0.477199,0.162046,0.616888,0.147529,...,0.246434,0.475312,0.089394,0.054476,0.400392,0.474080,0.100825,0.160666,0.387606,0.259186
AF,0.110109,0.279710,0.000000,0.491387,0.088694,0.243199,0.266081,0.239542,0.459024,0.181798,...,0.075048,0.735973,0.307910,0.298465,0.238524,0.275046,0.203129,0.136254,0.218217,0.050539
AG,0.499580,0.608565,0.491387,0.000000,0.480837,0.549335,0.329582,0.567287,0.184125,0.525429,...,0.546925,0.941052,0.645818,0.621536,0.661109,0.564104,0.524636,0.515682,0.303271,0.494749
AL,0.142680,0.211407,0.088694,0.480837,0.000000,0.175210,0.328596,0.177437,0.451913,0.116545,...,0.110486,0.670463,0.239420,0.226161,0.313895,0.349762,0.133962,0.067007,0.218101,0.092232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WS,0.333843,0.474080,0.275046,0.564104,0.349762,0.437107,0.315434,0.375714,0.518548,0.392832,...,0.253280,0.916505,0.483513,0.491022,0.203233,0.000000,0.431777,0.365949,0.352779,0.294249
YE,0.238355,0.100825,0.203129,0.524636,0.133962,0.094348,0.415964,0.119750,0.528747,0.069165,...,0.193680,0.555155,0.166953,0.116464,0.390138,0.431777,0.000000,0.086741,0.310130,0.183800
ZA,0.192933,0.160666,0.136254,0.515682,0.067007,0.118659,0.380959,0.117972,0.488031,0.061857,...,0.124768,0.614244,0.188925,0.173342,0.327330,0.365949,0.086741,0.000000,0.250714,0.131824
ZM,0.274351,0.387606,0.218217,0.303271,0.218101,0.343958,0.187388,0.317113,0.248159,0.278750,...,0.259550,0.837104,0.422232,0.404705,0.377565,0.352779,0.310130,0.250714,0.000000,0.249236
ZW,0.077526,0.259186,0.050539,0.494749,0.092232,0.246333,0.258800,0.244545,0.487869,0.189981,...,0.077206,0.714089,0.280896,0.273194,0.258496,0.294249,0.183800,0.131824,0.249236,0.000000

In [63]:
uf.plotly_heatmap(
    df_dist,
    x_labels=df_dist.columns,
    y_labels=df_dist.index,
    z_min=0, z_max=1,
    colorscale="non-symmetrical",
    x_type="country",
    y_type="country",
    title=f"Distance between countries, {mode[:-1]}, {year}",
)

In [64]:
# Example: distance matrix (symmetric, zeros on diagonal)
D = df_dist.values

# Convert to condensed form (required by linkage)
condensed_D = squareform(D)

# Perform hierarchical clustering
# method can be: 'single', 'complete', 'average', 'ward'
Z = linkage(condensed_D, method='average')

In [65]:
# Assign clusters by specifying a max distance threshold
labels = fcluster(Z, t=0.2, criterion='distance')
order = np.argsort(labels)
# print("Cluster labels:", labels)

In [66]:
labels = np.array(labels)

order = np.argsort(labels)
D_ordered = D[np.ix_(order, order)]

names = df_dist.index.to_numpy()
names_ordered = [uf.id2name_country[name] for name in names[order]]
labels_ordered = labels[order]

In [67]:
fig = go.Figure(
    data=go.Heatmap(
        z=D_ordered,
        x=names_ordered,
        y=names_ordered,
        colorscale="Viridis",
        colorbar=dict(title="Distance"),
        hovertemplate="Row: %{y}<br>Col: %{x}<br>Dist: %{z:.3f}<extra></extra>"
    )
)

fig.update_layout(
    title="Distance matrix reordered by cluster labels",
    xaxis=dict(
        tickangle=45,
        tickfont=dict(size=8),
        automargin=True
    ),
    yaxis=dict(
        tickfont=dict(size=8),
        automargin=True
    ),
    width=900,
    height=900
)
# cluster boundaries
changes = np.where(np.diff(labels_ordered) != 0)[0] + 1

for c in changes:
    fig.add_shape(
        type="line",
        x0=-0.5, x1=len(names_ordered)-0.5,
        y0=c-0.5, y1=c-0.5,
        line=dict(color="white", width=1)
    )
    fig.add_shape(
        type="line",
        x0=c-0.5, x1=c-0.5,
        y0=-0.5, y1=len(names_ordered)-0.5,
        line=dict(color="white", width=1)
    )

fig.show()

In [68]:
df_map = (
    df_dist
    .merge(uf.df_country[["alpha-2", "alpha-3", "name", "region", "sub-region"]], left_index=True, right_on="alpha-2", how="left")
    [["alpha-2", "alpha-3", "name", "sub-region", "region"]]
    .assign(cluster=labels,
            cluster_str = lambda df: df["cluster"].astype(str))
    .rename(columns={"alpha-3": "country", "alpha-2": "country2"})
)
df_map.sample(5)

,country2,country,name,sub-region,region,cluster,cluster_str
110,IT,ITA,Italy,Southern Europe,Europe,12,12
73,FO,FRO,Faroe Islands,Northern Europe,Europe,12,12
175,PH,PHL,Philippines,South-eastern Asia,Asia,14,14
118,KP,PRK,"Korea, Democratic People's Republic of",Eastern Asia,Asia,3,3
102,IS,ISL,Iceland,Northern Europe,Europe,12,12

In [69]:
fig = px.choropleth(
    df_map,
    locations="country",
    color="cluster_str",               # use the categorical version
    locationmode="ISO-3",
    color_discrete_sequence=px.colors.qualitative.Set3,  # discrete color palette
    title=f"Country clusters based on distance matrix, {mode[:-1]}, {year}"
)

fig.update_layout(
    geo=dict(
        showframe=False,
        showcoastlines=True,
        projection_type="natural earth"
    ),
    height=600,
)

fig.show()