In [1]:
import pandas as pd
import pyarrow.parquet as pq
import importlib

from tqdm import tqdm

import plotly.express as px
import prepare_data as prepare_data

In [2]:
PATH_FROM = "../data_clean/raw/"
PATH_TO = "../data_clean/"

# Prepare institutions and topics mappings

In [3]:
df_institutions_raw = pd.read_csv(PATH_FROM+"Maxime_institutions.csv", sep=";", decimal=",")

In [4]:
df_topics_raw = pd.read_csv(PATH_FROM+"Maxime_topics.csv", sep=";", decimal=",")

In [15]:
df_country = pd.read_csv(PATH_FROM+"Floriana_country_info.csv")

In [16]:
df_country

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,NaN,9.0,61.0,NaN
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,NaN,2.0,15.0,NaN
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,NaN,142.0,145.0,NaN
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0

In [21]:
(
    df_country[["alpha-2", "name", "region"]]
    .merge(df_institutions_raw[["Country_cleaned"]].drop_duplicates(), left_on="alpha-2", right_on="Country_cleaned", how="outer")
    .dropna(subset=["Country_cleaned"])
)

    alpha-2                  name    region Country_cleaned
0        AD               Andorra    Europe              AD
1        AE  United Arab Emirates      Asia              AE
2        AF           Afghanistan      Asia              AF
3        AG   Antigua and Barbuda  Americas              AG
5        AL               Albania    Europe              AL
..      ...                   ...       ...             ...
242      WS                 Samoa   Oceania              WS
243      YE                 Yemen      Asia              YE
245      ZA          South Africa    Africa              ZA
246      ZM                Zambia    Africa              ZM
247      ZW              Zimbabwe    Africa              ZW

[219 rows x 4 columns]

In [22]:
219 - 193

26

In [12]:
df_institutions_raw.Country_cleaned.unique()

array(['GB', 'US', 'CZ', 'KR', 'ES', 'TT', 'SE', 'MX', 'NG', 'SK', 'FR',
       'DE', 'NL', 'PT', 'NP', 'AT', 'AR', 'EC', 'CU', 'AU', 'IE', 'SI',
       'JP', 'GH', 'BF', 'IN', 'SB', 'CN', 'ID', 'CH', 'IT', 'BR', 'RU',
       'PL', 'NO', 'GR', 'MZ', 'CA', 'PH', 'LU', 'BW', 'BE', 'SA', 'IQ',
       'EG', 'SO', 'ZW', 'SY', 'DO', 'UZ', 'NZ', 'DZ', 'HR', 'TN', 'HU',
       'TR', 'VI', 'ME', 'ZA', 'CO', 'VN', 'UG', 'BJ', 'DK', 'RO', 'CI',
       'MR', 'MA', 'UA', 'MY', 'BD', 'IR', 'ET', 'AE', 'CM', 'AO', 'HK',
       'IL', 'TW', 'FI', 'CL', 'SG', 'TH', 'MO', 'LB', 'QA', 'CY', 'LT',
       'KW', 'UY', 'KE', 'SS', 'PK', 'CR', 'EE', 'VE', 'LK', 'PR', 'LV',
       'GE', 'JM', 'BI', 'RS', 'TJ', 'BN', 'TZ', 'AZ', 'BG', 'MK', 'PE',
       'VG', 'JO', 'BA', 'MU', 'KH', 'NE', 'PS', 'CD', 'YE', 'BY', 'MM',
       'MC', 'BH', 'KZ', 'OM', 'ML', 'MN', 'GL', 'SN', 'ST', 'GA', 'CG',
       'GT', 'LI', 'IS', 'GF', 'MG', 'PA', 'LY', 'BO', 'SD', 'AL', 'RE',
       'HN', 'GP', 'AM', 'SZ', nan, 'MW', 'RW', 'LA', 'ZM', 'SC', 'CF',
       'VU', 'BZ', 'VA', 'SL', 'BT', 'WS', 'GN', 'SJ', 'KP', 'MT', 'MD',
       'KG', 'SV', 'PG', 'AD', 'AF', 'GM', 'FJ', 'TG', 'HT', 'BB', 'TL',
       'FO', 'PY', 'PW', 'GW', 'NI', 'FM', 'TC', 'LR', 'DJ', 'LC', 'BS',
       'SR', 'GD', 'PF', 'KI', 'AS', 'MV', 'MP', 'GY', 'KN', 'TD', 'GU',
       'CV', 'TM', 'FK', 'GI', 'DM', 'BM', 'LS', 'KY', 'VC', 'MQ', 'TV',
       'CK', 'EH', 'SM', 'AG', 'GQ', 'NC', 'ER', 'MS', 'AW', 'TO', 'NU'],
      dtype=object)

In [67]:
df_topics = (
    df_topics_raw
    .rename(columns={"ID": "topic_id", "Name": "topic_name",
                     "Sub_ID": "subfield_id", "Sub_Name": "subfield_name",
                     "Field_ID": "field_id", "Field_Name": "field_name",
                     "Domain_ID": "domain_id", "Domain_Name": "domain_name"})
    .drop_duplicates()
)
df_topics.to_csv(PATH_TO+"df_topics.csv", index=False)

In [6]:
df_institutions = (
    df_institutions_raw
    [["ID", "Country_cleaned"]]
    .rename(columns={"Country_cleaned": "country", "ID": "institution_id"})
    .drop_duplicates()
)

# Clean data one year

In [23]:
year = "2023"
parqToRead=PATH_FROM+"authorsPapersTopicsYearInstitutions.parquet"

columns = ["authors", "id", "year", "institution", "topic"]

table = pq.read_table(parqToRead, columns=columns, filters=[('year','=',year)])
df_year = table.to_pandas()

In [25]:
df_year.id.nunique()

4729415

In [31]:
list(set(df_year.authors))

['A5075779143',
 'A5043292005',
 'A5085830552',
 'A5049171573',
 'A5103158764',
 'A5028723452',
 'A5104203697',
 'A5056009167',
 'A5012819477',
 'A5078070740',
 'A5093546450',
 'A5008675640',
 'A5073694598',
 'A5101962389',
 'A5102796202',
 'A5018398974',
 'A5093261546',
 'A5037310068',
 'A5077953768',
 'A5033548012',
 'A5071829800',
 'A5055186794',
 'A5064041125',
 'A5024918504',
 'A5031156444',
 'A5100521119',
 'A5027578199',
 'A5013224319',
 'A5014348129',
 'A5013523535',
 'A5048554573',
 'A5021544759',
 'A5069543493',
 'A5023819217',
 'A5037990039',
 'A5008095251',
 'A5048998165',
 'A5039153063',
 'A5042685051',
 'A5066629403',
 'A5049360259',
 'A5101188625',
 'A5034218002',
 'A5019208005',
 'A5036547376',
 'A5054870369',
 'A5007033501',
 'A5100906643',
 'A5044413679',
 'A5050315491',
 'A5044283996',
 'A5050253741',
 'A5047250114',
 'A5082364495',
 'A5019568144',
 'A5101026931',
 'A5054468787',
 'A5086485401',
 'A5035975344',
 'A5060188217',
 'A5085768615',
 'A5011187627',
 'A5103139476',
 'A5082154839',
 'A5093364028',
 'A5092056051',
 'A5010519069',
 'A5051253743',
 'A5101847539',
 'A5063715401',
 'A5007322464',
 'A5092385722',
 'A5055050920',
 'A5079878174',
 'A5087412648',
 'A5038133469',
 'A5092483928',
 'A5054344776',
 'A5093623503',
 'A5028327912',
 'A5005964875',
 'A5009539975',
 'A5046848814',
 'A5029595764',
 'A5011496799',
 'A5054096253',
 'A5072363031',
 'A5092625747',
 'A5087402868',
 'A5092958401',
 'A5028293798',
 'A5100429496',
 'A5007895815',
 'A5025231238',
 'A5085212245',
 'A5092508076',
 'A5101644175',
 'A5093436496',
 'A5000508387',
 'A5045856914',
 'A5072467019',
 'A5058842127',
 'A5015274423',
 'A5056029007',
 'A5103242196',
 'A5027858731',
 'A5012269885',
 'A5002192552',
 'A5040743886',
 'A5062275346',
 'A5093631847',
 'A5087076981',
 'A5020039975',
 'A5017733225',
 'A5057732985',
 'A5083063241',
 'A5030033508',
 'A5024951735',
 'A5019420695',
 'A5102131626',
 'A5093491004',
 'A5002614050',
 'A5053380355',
 'A5007061241',
 'A5088453202',
 'A5009319569',
 'A5094054771',
 'A5013043778',
 'A5031112530',
 'A5000794291',
 'A5019631275',
 'A5095331469',
 'A5092351722',
 'A5086022040',
 'A5051213584',
 'A5068376395',
 'A5052173452',
 'A5035999553',
 'A5085789654',
 'A5013666696',
 'A5051183374',
 'A5067024898',
 'A5052938357',
 'A5063715654',
 'A5061647360',
 'A5104229828',
 'A5062838601',
 'A5098903439',
 'A5091936734',
 'A5066010990',
 'A5100628812',
 'A5092681534',
 'A5104181191',
 'A5091672785',
 'A5065244352',
 'A5104561651',
 'A5061492808',
 'A5060351823',
 'A5054108490',
 'A5101086562',
 'A5032068341',
 'A5088445653',
 'A5100943374',
 'A5104188475',
 'A5004153889',
 'A5025926091',
 'A5059592706',
 'A5089486689',
 'A5068201700',
 'A5103093364',
 'A5092016286',
 'A5091084906',
 'A5084884571',
 'A5064221068',
 'A5031762057',
 'A5022014219',
 'A5036902259',
 'A5020102478',
 'A5102754098',
 'A5040230996',
 'A5104171416',
 'A5057402553',
 'A5101985728',
 'A5080185006',
 'A5033082288',
 'A5081993297',
 'A5037012083',
 'A5032583065',
 'A5090716019',
 'A5038331995',
 'A5043106525',
 'A5000572251',
 'A5043962848',
 'A5103955915',
 'A5080807854',
 'A5002200665',
 'A5008288955',
 'A5012623143',
 'A5069639653',
 'A5025678950',
 'A5011941254',
 'A5066014893',
 'A5055433736',
 'A5010289715',
 'A5040318790',
 'A5026442433',
 'A5104237457',
 'A5022238072',
 'A5010168461',
 'A5069149831',
 'A5062591829',
 'A5102724454',
 'A5101194382',
 'A5063596268',
 'A5088269389',
 'A5101239752',
 'A5012757535',
 'A5048809700',
 'A5093659907',
 'A5018185887',
 'A5040438161',
 'A5092709480',
 'A5061749804',
 'A5074046582',
 'A5100368114',
 'A5024759803',
 'A5101245622',
 'A5100382257',
 'A5066156541',
 'A5092860248',
 'A5018090129',
 'A5033389062',
 'A5029033680',
 'A5067581219',
 'A5101442104',
 'A5007238891',
 'A5035693270',
 'A5064000677',
 'A5102595956',
 'A5010051479',
 'A5092878882',
 'A5061189300',
 'A5042100938',
 'A5052420510',
 'A5012958743',
 'A5065650677',
 'A5055023619',
 'A5001477973',
 'A5005477291',
 'A5080577794',
 'A5100422202',
 'A5061359466',
 'A5093034480',
 'A5004220544',
 'A5083521577',
 'A5004037772',
 'A5000455894',
 'A5002960434',
 'A5020136423',
 'A5027826379',
 'A5009075884',
 'A5009940953',
 'A5104139084',
 'A5045373447',
 'A5052944225',
 'A5082105666',
 'A5048349836',
 'A5062316867',
 'A5071739830',
 'A5008152783',
 'A5033007512',
 'A5090792671',
 'A5104195832',
 'A5031964289',
 'A5082230912',
 'A5093118130',
 'A5076265592',
 'A5012918789',
 'A5087886430',
 'A5032673604',
 'A5033127584',
 'A5103154584',
 'A5094071335',
 'A5102734829',
 'A5015953144',
 'A5061454385',
 'A5092101235',
 'A5054957281',
 'A5034315761',
 'A5103024904',
 'A5054525235',
 'A5077812104',
 'A5043908394',
 'A5033043001',
 'A5058535460',
 'A5093771459',
 'A5093147351',
 'A5074944673',
 'A5015970180',
 'A5039223590',
 'A5093868756',
 'A5078384264',
 'A5013986139',
 'A5093210695',
 'A5013314763',
 'A5102786015',
 'A5017249714',
 'A5043204832',
 'A5026686927',
 'A5082691448',
 'A5050626874',
 'A5100522167',
 'A5037001958',
 'A5092111867',
 'A5084434549',
 'A5068464092',
 'A5078541515',
 'A5047076529',
 'A5065331508',
 'A5046754186',
 'A5079896191',
 'A5058603886',
 'A5048020632',
 'A5102661366',
 'A5052158539',
 'A5049343668',
 'A5059625464',
 'A5025877387',
 'A5101227574',
 'A5074010119',
 'A5062465162',
 'A5016237482',
 'A5026007781',
 'A5079024906',
 'A5089600752',
 'A5092668272',
 'A5036559316',
 'A5068630102',
 'A5083824089',
 'A5005461646',
 'A5083266880',
 'A5058377281',
 'A5096971786',
 'A5039302571',
 'A5017597311',
 'A5002802859',
 'A5002889302',
 'A5061523923',
 'A5055464473',
 'A5073882333',
 'A5058599678',
 'A5059250020',
 'A5010461528',
 'A5100352161',
 'A5028490781',
 'A5070442073',
 'A5087340296',
 'A5074980805',
 'A5030925408',
 'A5031373792',
 'A5073802183',
 'A5057833086',
 'A5055740625',
 'A5001997901',
 'A5092042523',
 'A5094578928',
 'A5103044637',
 'A5000569978',
 'A5092557722',
 'A5004150830',
 'A5056599112',
 'A5029637575',
 'A5074512935',
 'A5014849418',
 'A5015870275',
 'A5102967715',
 'A5100351939',
 'A5062226843',
 'A5101694353',
 'A5046276144',
 'A5102506239',
 'A5040786994',
 'A5066195526',
 'A5104630160',
 'A5060567585',
 'A5010917256',
 'A5069648009',
 'A5075910791',
 'A5035403043',
 'A5049206371',
 'A5101682368',
 'A5101025629',
 'A5082644645',
 'A5068559539',
 'A5080861265',
 'A5061699083',
 'A5092055452',
 'A5101912962',
 'A5016055566',
 'A5036364399',
 'A5031479229',
 'A5052977603',
 'A5057665487',
 'A5057555714',
 'A5055048737',
 'A5049285461',
 'A5008955887',
 'A5031494122',
 'A5073422963',
 'A5049928655',
 'A5029232186',
 'A5019289346',
 'A5093187690',
 'A5030306649',
 'A5060722184',
 'A5020591269',
 'A5049155074',
 'A5034725208',
 'A5102013158',
 'A5013833475',
 'A5092216294',
 'A5012169345',
 'A5021245341',
 'A5078745592',
 'A5017096326',
 'A5027950728',
 'A5051123438',
 'A5038430050',
 'A5048688294',
 'A5086995490',
 'A5055671856',
 'A5046686987',
 'A5059120798',
 'A5003330079',
 'A5002799251',
 'A5100326757',
 'A5054311081',
 'A5065827398',
 'A5037703950',
 'A5071208401',
 'A5051548543',
 'A5101595500',
 'A5017871167',
 'A5048405028',
 'A5048215821',
 'A5092976470',
 'A5035495782',
 'A5005284344',
 'A5084626038',
 'A5100390035',
 'A5090609611',
 'A5070127033',
 'A5076476770',
 'A5075435082',
 'A5056483193',
 'A5105878764',
 'A5030628621',
 'A5097929645',
 'A5041805862',
 'A5100357476',
 'A5056782112',
 'A5065016389',
 'A5092848539',
 'A5068764086',
 'A5042092849',
 'A5044631695',
 'A5089645165',
 'A5082566589',
 'A5021467860',
 'A5014996483',
 'A5093060377',
 'A5061829482',
 'A5036911408',
 'A5086901514',
 'A5023083851',
 'A5073014832',
 'A5091408910',
 'A5086323169',
 'A5048228788',
 'A5013004440',
 'A5029276449',
 'A5073069233',
 'A5067130854',
 'A5017163593',
 'A5038526098',
 'A5093084120',
 'A5095312540',
 'A5022710027',
 'A5052057063',
 'A5022203580',
 'A5076133908',
 'A5022978855',
 'A5057707695',
 'A5065988587',
 'A5047907579',
 'A5064829103',
 'A5037072718',
 'A5076234418',
 'A5058821318',
 'A5073140509',
 'A5069126706',
 'A5029828179',
 'A5035699145',
 'A5068505205',
 'A5037520334',
 'A5061178637',
 'A5092469177',
 'A5067690976',
 'A5077630975',
 'A5092986935',
 'A5101950558',
 'A5092147174',
 'A5104160619',
 'A5021103578',
 'A5036863522',
 'A5058123297',
 'A5102590475',
 'A5092102334',
 'A5101179509',
 'A5100767737',
 'A5098215586',
 'A5074654163',
 'A5093670760',
 'A5092144152',
 'A5036581715',
 'A5042262680',
 'A5073190927',
 'A5102802040',
 'A5020989806',
 'A5046925535',
 'A5006725420',
 'A5057328231',
 'A5002845079',
 'A5041632305',
 'A5076122709',
 'A5053734641',
 'A5017774880',
 'A5104198867',
 'A5019682875',
 'A5002857122',
 'A5077479655',
 'A5051015797',
 'A5066126611',
 'A5098672226',
 'A5028013205',
 'A5053862385',
 'A5093585049',
 'A5078426510',
 'A5092128713',
 'A5071678080',
 'A5009862291',
 'A5085290390',
 'A5076731160',
 'A5103786586',
 'A5049137007',
 'A5070862323',
 'A5093139438',
 'A5092508542',
 'A5064884764',
 'A5056001873',
 'A5037725253',
 'A5005497664',
 'A5006018976',
 'A5064781827',
 'A5005045987',
 'A5067803466',
 'A5028667682',
 'A5101814742',
 'A5070127492',
 'A5091712864',
 'A5093640337',
 'A5103574073',
 'A5081807536',
 'A5008410268',
 'A5040337551',
 'A5027532571',
 'A5069527234',
 'A5022326802',
 'A5092775244',
 'A5051908599',
 'A5044269445',
 'A5100945767',
 'A5093346474',
 'A5013958479',
 'A5092900955',
 'A5065127746',
 'A5051459336',
 'A5038523827',
 'A5100776697',
 'A5004374418',
 'A5100873340',
 'A5014897253',
 'A5052413718',
 'A5059075421',
 'A5012719309',
 'A5030511364',
 'A5027174473',
 'A5071161208',
 'A5046166015',
 'A5044048905',
 'A5037441003',
 'A5053743100',
 'A5092507321',
 'A5086462083',
 'A5026886468',
 'A5036237483',
 'A5018114694',
 'A5102405604',
 'A5092221217',
 'A5100443278',
 'A5073739135',
 'A5081495955',
 'A5022209861',
 'A5025747494',
 'A5001932777',
 'A5010895376',
 'A5000312904',
 'A5065284490',
 'A5026001875',
 'A5093956521',
 'A5070706459',
 'A5023661918',
 'A5021740865',
 'A5008808717',
 'A5090459925',
 'A5087516741',
 'A5092873853',
 'A5023540932',
 'A5103687917',
 'A5100726046',
 'A5101625914',
 'A5015222117',
 'A5081682513',
 'A5084957215',
 'A5092910716',
 'A5040027493',
 'A5066954007',
 'A5062491789',
 'A5014079230',
 'A5093424464',
 'A5067395691',
 'A5018856264',
 'A5071568663',
 'A5098687596',
 'A5000740593',
 'A5027563727',
 'A5053088153',
 'A5092508398',
 'A5100321804',
 'A5070760888',
 'A5018710697',
 'A5092153746',
 'A5092817558',
 'A5040730825',
 'A5100584136',
 'A5043707370',
 'A5000658042',
 'A5015733212',
 'A5064940915',
 'A5005901904',
 'A5101606970',
 'A5083921011',
 'A5025685996',
 'A5016690973',
 'A5060596443',
 'A5093009587',
 'A5033516239',
 'A5102948409',
 'A5092065027',
 'A5040298086',
 'A5028705870',
 'A5078847282',
 'A5045653243',
 'A5090211098',
 'A5057288348',
 'A5008585662',
 'A5048438241',
 'A5101735548',
 'A5061116979',
 'A5013500328',
 'A5070623553',
 'A5104170633',
 'A5087054249',
 'A5051864776',
 'A5075276041',
 'A5065942189',
 'A5003396772',
 'A5059039015',
 'A5101897583',
 'A5033180428',
 'A5100687663',
 'A5024752000',
 'A5100647662',
 'A5081849547',
 'A5025489079',
 'A5003940244',
 'A5007838938',
 'A5100911440',
 'A5102628399',
 'A5014928125',
 'A5039123375',
 'A5002108384',
 'A5005822293',
 'A5004291994',
 'A5077159418',
 'A5091909710',
 'A5092756356',
 'A5051897828',
 'A5073862712',
 'A5093284779',
 'A5050533485',
 'A5077161380',
 'A5065453303',
 'A5052938483',
 'A5042390976',
 'A5064619027',
 'A5035947394',
 'A5058188369',
 'A5043866772',
 'A5090057958',
 'A5086715042',
 'A5082557937',
 'A5042781252',
 'A5095316842',
 'A5104532710',
 'A5095314950',
 'A5021747010',
 'A5044313755',
 'A5083040133',
 'A5103227765',
 'A5103466064',
 'A5088940202',
 'A5014561641',
 'A5006704641',
 'A5032825052',
 'A5055098362',
 'A5045663649',
 'A5059781213',
 'A5062516758',
 'A5038070314',
 'A5027203087',
 'A5092396591',
 'A5078412415',
 'A5052285507',
 'A5020684814',
 'A5086422039',
 'A5100880629',
 'A5050282787',
 'A5081254985',
 'A5080442635',
 'A5062110028',
 'A5092782623',
 'A5101714822',
 'A5104557898',
 'A5010943905',
 'A5073917431',
 'A5101173902',
 'A5087442668',
 'A5012884492',
 'A5052682990',
 'A5056925613',
 'A5051009786',
 'A5070383838',
 'A5060331457',
 'A5093756451',
 'A5088198408',
 'A5101864078',
 'A5033986771',
 'A5018008591',
 'A5040829075',
 'A5004092640',
 'A5017266753',
 'A5038303086',
 'A5059192211',
 'A5033246512',
 'A5090100239',
 'A5103421421',
 'A5023261377',
 'A5019594744',
 'A5092130463',
 'A5027251964',
 'A5060509854',
 'A5006953944',
 'A5008875656',
 'A5104221843',
 'A5066615234',
 'A5060165643',
 'A5047246430',
 'A5092914320',
 'A5006347078',
 'A5093677950',
 'A5101282369',
 'A5000572553',
 'A5010809166',
 'A5046765910',
 'A5098776434',
 'A5102202792',
 'A5092431394',
 'A5015190437',
 'A5047174090',
 'A5068084366',
 'A5057575913',
 'A5055215215',
 'A5067711649',
 'A5102090820',
 'A5025134473',
 'A5039752603',
 'A5052105099',
 'A5015487817',
 'A5026235875',
 'A5093454344',
 'A5057320015',
 'A5090866945',
 'A5072069945',
 'A5007530963',
 'A5087057309',
 'A5079445024',
 'A5036164075',
 'A5011171046',
 'A5015764704',
 'A5092184024',
 'A5032712724',
 'A5043975261',
 'A5101574923',
 'A5079624270',
 'A5067132918',
 'A5068864671',
 'A5014996359',
 'A5057960212',
 'A5082782104',
 'A5069232261',
 'A5072596721',
 'A5009730025',
 'A5093933425',
 'A5005261557',
 'A5038539783',
 'A5100387363',
 'A5050885508',
 'A5040555706',
 'A5018244164',
 'A5060241853',
 'A5024385979',
 'A5041677650',
 'A5000303620',
 'A5075409573',
 'A5088267118',
 'A5101452878',
 'A5044194354',
 'A5085076031',
 'A5024788937',
 'A5072976916',
 'A5086492257',
 'A5039074178',
 'A5061820874',
 'A5092555250',
 'A5104219896',
 'A5093982036',
 'A5092866360',
 'A5103065118',
 'A5005063509',
 'A5025178670',
 'A5103036372',
 'A5066488818',
 'A5044559446',
 'A5039832092',
 'A5024912621',
 'A5092911240',
 'A5038251447',
 'A5009170645',
 'A5051215536',
 'A5092541635',
 'A5072409625',
 'A5060871525',
 'A5098975303',
 'A5051994970',
 'A5021235115',
 'A5104152361',
 'A5000483561',
 'A5101714493',
 'A5083026298',
 'A5060935112',
 'A5077043379',
 'A5104133236',
 'A5104208973',
 'A5092557379',
 'A5069420016',
 'A5031814034',
 'A5101782495',
 'A5056193352',
 'A5081063151',
 'A5066782579',
 'A5043622807',
 'A5081608465',
 'A5103110753',
 'A5022479572',
 'A5101776600',
 'A5020187014',
 'A5003921480',
 'A5092929939',
 'A5101324162',
 'A5036834015',
 'A5005753891',
 'A5039660434',
 'A5007704496',
 'A5092386220',
 'A5011359513',
 'A5081754762',
 'A5044464536',
 'A5049438225',
 'A5037165857',
 'A5020830996',
 'A5003314648',
 'A5015122881',
 'A5034772051',
 'A5062724400',
 'A5018332747',
 'A5067265411',
 'A5066045452',
 'A5038617841',
 'A5102876655',
 'A5009608137',
 'A5022240108',
 'A5101184936',
 'A5059045764',
 'A5047968614',
 'A5100664515',
 'A5088184281',
 'A5051572048',
 'A5001499840',
 'A5031639626',
 'A5091963466',
 'A5092895547',
 'A5100351464',
 'A5087030693',
 'A5017044487',
 'A5064599918',
 'A5084504582',
 'A5056390532',
 'A5002807932',
 'A5079085175',
 'A5094192830',
 'A5076809586',
 'A5060709720',
 'A5006087367',
 'A5100347361',
 'A5037956982',
 'A5102387533',
 'A5000564756',
 'A5028587494',
 'A5059353375',
 'A5041433249',
 'A5056184584',
 'A5037328960',
 'A5085855492',
 'A5012185388',
 'A5036382251',
 'A5009130463',
 'A5018884062',
 'A5012464415',
 'A5092728108',
 'A5057378374',
 'A5015759705',
 'A5089271094',
 'A5033274841',
 'A5071139588',
 'A5102221260',
 'A5102024876',
 'A5091919912',
 'A5032564764',
 'A5004572955',
 'A5002937098',
 'A5093617901',
 'A5047080459',
 'A5003107794',
 'A5101215150',
 'A5062135952',
 'A5075328931',
 'A5087945111',
 'A5092102918',
 'A5001431023',
 'A5061781147',
 'A5091925170',
 'A5104221312',
 'A5046874084',
 'A5020394124',
 'A5036249635',
 'A5063025643',
 'A5084445897',
 'A5101245925',
 'A5101893801',
 'A5100812705',
 'A5103117440',
 'A5032311799',
 'A5020753116',
 'A5069768584',
 'A5055880983',
 'A5101456126',
 'A5092000249',
 'A5050634724',
 'A5019992082',
 ...]

In [10]:
df_article_subfield_country = prepare_data.get_article_subfield_country(df_year,
                                                                        df_topics,
                                                                        df_institutions).dropna(subset=["country"])

In [ ]:
df_country_subfield_individual = (
    df_article_subfield_country
    .query("n_countries == 1")
    [["article_id", "country", "subfield_id"]]
    .groupby(["country", "subfield_id"], as_index=False)
    .count()
    .pivot(index="country", columns="subfield_id", values="article_id")
)

df_country_subfield_collaborative = (
    df_article_subfield_country
    .query("n_countries > 1")
    [["article_id", "country", "subfield_id"]]
    .groupby(["country", "subfield_id"], as_index=False)
    .count()
    .pivot(index="country", columns="subfield_id", values="article_id")
)

# Clean data pipeline

In [15]:
parqToRead=PATH_FROM+'authorsPapersTopicsYearInstitutions.parquet'
columns = ["authors", "id", "year", "institution", "topic"]

In [17]:
df_country_subfield_individual_list = []
df_country_subfield_collaborative_list = []

In [39]:
start_year = 1970
end_year = 2023

n_articles = 0
# authors_list = []
for year_loop in tqdm(range(start_year, end_year + 1)):
    table = pq.read_table(parqToRead, columns=columns, filters=[('year','=',str(year_loop))])
    df_year = table.to_pandas()

    n_articles += df_year.id.nunique()
    # authors_list += list(set(df_year.authors))
    
# df_global_comparison_yearly = pd.concat(df_global_comparison_list)
# df_global_comparison_yearly.to_csv(uf.PATH+f"df_global_comparison_yearly.csv")

100%|██████████| 54/54 [09:02<00:00, 10.04s/it]

In [ ]:
# len(authors_list)

115851691

In [40]:
n_articles

79093264

In [37]:
len(list(set(authors_list)))

32806409

In [ ]:
start_year = 1970
end_year = 2023

for year_loop in tqdm(range(start_year, end_year + 1)):
    table = pq.read_table(parqToRead, columns=columns, filters=[('year','=',str(year_loop))])
    df_year = table.to_pandas()

    df_article_subfield_country = prepare_data.get_article_subfield_country(df_year, df_topics, df_institutions)


    df_country_subfield_individual_list.append(
        df_article_subfield_country
        .query("n_countries == 1")
        [["article_id", "country", "subfield_id"]]
        .groupby(["country", "subfield_id"], as_index=False)
        .count()
        .pivot(index="country", columns="subfield_id", values="article_id")
        .assign(
            year = year_loop,
            mode = "individual"
        )
    )

    df_country_subfield_collaborative_list.append(
        df_article_subfield_country
        .query("n_countries > 1")
        [["article_id", "country", "subfield_id"]]
        .groupby(["country", "subfield_id"], as_index=False)
        .count()
        .pivot(index="country", columns="subfield_id", values="article_id")
        .assign(
            year = year_loop,
            mode = "collaborative"
        )
    )

df_country_subfield_yearly = (
    pd.concat(df_country_subfield_individual_list + df_country_subfield_collaborative_list)
    .reset_index()
    .set_index(["country", "year", "mode"])
)
# df_global_comparison_yearly = pd.concat(df_global_comparison_list)
# df_global_comparison_yearly.to_csv(uf.PATH+f"df_global_comparison_yearly.csv")

  0%|          | 0/44 [00:12<?, ?it/s]

KeyboardInterrupt:

In [ ]:
n_years = 5

df_country_subfield_rolling_yearly = (
    df_country_subfield_yearly
    .sort_index()
    .groupby(level=[0, 2])
    .rolling(n_years).sum()
    .reset_index(level=[0, 1], drop=True)
    .dropna(how="all")
)

In [ ]:
df_country_subfield_yearly.to_csv(PATH_TO+"df_ccountry_subfield.csv")
df_country_subfield_rolling_yearly.to_csv(PATH_TO+"df_country_subfield_roll_5y.csv")